buildscript {
    repositories {
        google()
        mavenCentral()
        // jcenter() is deprecated, using mavenCentral() instead
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.4'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        // jcenter() is deprecated, using mavenCentral() instead
    }
}

apply plugin: 'com.android.application'

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    
    // AndroidX Core SplashScreen library for Android 12+ splash screen API
    implementation 'androidx.core:core-splashscreen:1.0.1'
}

android {
    /*******************************************************
     * The following variables:
     * - androidBuildToolsVersion,
     * - androidCompileSdkVersion
     * - qt5AndroidDir - holds the path to qt android files
     *                   needed to build any Qt application
     *                   on Android.
     *
     * are defined in gradle.properties file. This file is
     * updated by QtCreator and androiddeployqt tools.
     * Changing them manually might break the compilation!
     *******************************************************/

    namespace 'org.Orayta'
    compileSdkVersion androidCompileSdkVersion.toInteger()
    
    // Build tools version compatible with Qt 6.5.3 and SDK 35
    buildToolsVersion "34.0.0"
    
    // Configure Java compatibility for Android 16
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    
    // Default configuration for Android 9.0+ support
    defaultConfig {
        minSdkVersion 28  // Android 9.0 (Qt 6.6+ requirement)
        targetSdkVersion 35  // Android 15
        versionCode 96
        versionName "0.96"
    }
    
    // Signing configurations
    signingConfigs {
        debug {
            // Use default debug keystore
            storeFile file(System.getProperty("user.home") + "/.android/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }
    
    // Build types
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
            debuggable true
            minifyEnabled false
        }
        release {
            signingConfig signingConfigs.debug  // Use debug signing for now
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = [qt5AndroidDir + '/src', 'src', 'java']
            aidl.srcDirs = [qt5AndroidDir + '/src', 'src', 'aidl']
            res.srcDirs = [qt5AndroidDir + '/res', 'res']
            resources.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
       }
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }
    
    // Packaging options to handle duplicate files
    packaging {
        jniLibs {
            pickFirsts += ['**/libc++_shared.so', '**/libomp.so']
            useLegacyPackaging = true
        }
    }
    
    // Enable 16KB page size support
    bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = false
        }
        abi {
            enableSplit = false
        }
    }
}
